"""Build dependency-free static pages. Configure the real domain before publishing."""
import json
import re
from pathlib import Path
from html import escape
from urllib.parse import quote, urlparse
from xml.sax.saxutils import escape as xml_escape

ROOT = Path(__file__).resolve().parents[1]
config = json.loads((ROOT / 'site-config.json').read_text(encoding='utf-8'))
domain = config['domain'].rstrip('/')
if domain:
    parsed = urlparse(domain)
    if parsed.scheme != 'https' or not parsed.hostname or parsed.query or parsed.fragment or parsed.path not in ('', '/') or parsed.username or parsed.password:
        raise ValueError('domain must be the real HTTPS origin, e.g. https://your-academy.in')
phone = config['phone']
if not re.fullmatch(r'\+91\d{10}', phone):
    raise ValueError('phone must contain +91 followed by ten digits')
email = escape(config['email'])
address = escape(config['streetAddress']) + ', Hyderabad, Telangana ' + escape(config['postalCode'])
whatsapp = 'https://wa.me/' + phone.lstrip('+')
directions = 'https://www.google.com/maps/search/?api=1&query=' + quote(config['streetAddress'] + ', Hyderabad ' + config['postalCode'])
NAV = [('courses-page.html','Programs'),('abacus-page.html','Abacus'),('about-page.html','About us'),('online-abacus-classes.html','Online classes')]
PAGES = {}

def image(src, alt, width, height, eager=False, cls=''):
    return f'<img src="assets/images/{src}.webp" alt="{escape(alt)}" width="{width}" height="{height}" class="{cls}" {"fetchpriority=high" if eager else "loading=lazy"} decoding="async">'

def brand():
    return '<a class="brand" href="index.html" aria-label="The Numbers Academy home"><span class="brand-mark" aria-hidden="true"><img src="assets/images/academy-logo.webp" alt="" width="52" height="52"></span><span>The Numbers Academy<small>LITTLE MINDS. BIG POSSIBILITIES.</small></span></a>'

def render(path, title, description, content, schema=None):
    PAGES[path] = title
    canonical = domain + '/' + ('' if path == 'index.html' else quote(path))
    seo = f'<link rel="canonical" href="{canonical}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{domain}/assets/images/learning-hero.webp"><meta name="twitter:image" content="{domain}/assets/images/learning-hero.webp">' if domain else ''
    nav = ''.join(f'<a href="{href}" {"aria-current=page" if href == path else ""}>{label}</a>' for href,label in NAV)
    structured = '<script type="application/ld+json">' + json.dumps(schema, ensure_ascii=False).replace('<','\\u003c') + '</script>' if schema else ''
    footer = f'''<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div>{brand()}<p>Making numbers feel like possibilities.<br>Abacus, Vedic Maths &amp; Rubik’s Cube learning.</p></div><div><h3>Explore programs</h3><a href="abacus-page.html">Abacus</a><a href="vedic-math-page.html">Vedic Maths</a><a href="rubiks-cube-page.html">Rubik’s Cube</a></div><div><h3>Learn your way</h3><a href="abacus-classes-hyderabad.html">Hyderabad classes</a><a href="online-abacus-classes.html">Online abacus classes</a><a href="about-page.html">About the academy</a><a href="contact-page.html">Contact us</a></div><div><h3>Come say hello</h3><p>{address}</p><a href="tel:{phone}">{phone[:3]} {phone[3:]}</a><a href="mailto:{email}">{email}</a></div></div><div class="footer-bottom"><span>© The Numbers Academy. Empowering young minds.</span><span>Vidya Nagar, Hyderabad · Online learning</span></div></div></footer>'''
    html = f'''<!doctype html>
<html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | The Numbers Academy</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#19584a"><meta property="og:type" content="website"><meta property="og:site_name" content="The Numbers Academy"><meta property="og:locale" content="en_IN"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta name="twitter:card" content="summary_large_image">{seo}<link rel="icon" href="assets/favicon.png" type="image/png"><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script>{structured}</head>
<body><a class="skip" href="#main">Skip to content</a><div class="announcement">A little practice. A world of confidence. <a href="abacus-classes-hyderabad.html">Hyderabad</a> &amp; <a href="online-abacus-classes.html">online classes ↗</a></div><header class="site-header"><nav class="wrap nav" aria-label="Main navigation">{brand()}<button class="menu-toggle" aria-expanded="false" aria-controls="main-navigation" aria-label="Toggle navigation">☰</button><div class="nav-links" id="main-navigation">{nav}<a class="button" href="contact-page.html" {"aria-current=page" if path == "contact-page.html" else ""}>Enquire now <span aria-hidden="true">↗</span></a></div></nav></header><main id="main">{content}</main>{footer}</body></html>'''
    (ROOT / path).write_text(html, encoding='utf-8')

def cta():
    return '<section class="wrap bottom-space"><div class="cta"><div><span class="eyebrow" style="color:#ffcca5">LET’S GET STARTED</span><h2>Big possibilities begin with a small hello.</h2><p>Tell us about your child. We’ll help you explore the right program.</p></div><a class="button light" href="contact-page.html">Talk to the academy ↗</a></div></section>'

def cards():
    programs = [('abacus','Abacus training','Hands-on learning','Build a foundation in numbers, then work towards mental arithmetic.','abacus-page.html','Soroban abacus used for arithmetic practice',780,585),('vedic','Vedic Maths','Think beyond the textbook','Explore practical calculation strategies for multiplication, division and more.','vedic-math-page.html','Vedic Mathematics learning illustration',910,550),('cube','Rubik’s Cube','A colourful challenge','Discover patterns, follow a solving method and practise step by step.','rubiks-cube-page.html','Colourful Rubik’s Cube puzzle',675,380)]
    return '<div class="grid">' + ''.join(f'<article class="card"><div class="card-image">{image(src,alt,w,h)}</div><div class="card-body"><span class="badge">{badge}</span><h3>{name}</h3><p>{text}</p><a href="{href}">Explore the program <span aria-hidden="true">↗</span></a></div></article>' for src,name,badge,text,href,alt,w,h in programs) + '</div>'

def head(title, intro, eyebrow='LEARN. PRACTISE. GROW.'):
    return f'<div class="wrap"><header class="page-head"><div class="breadcrumbs"><a href="index.html">Home</a> / {escape(title)}</div><span class="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></header></div>'

def modes():
    return f'''<section class="section wrap"><span class="eyebrow">YOUR ROUTINE. YOUR WAY.</span><h2>One learning journey.<br>Two ways to join.</h2><div class="modes"><article class="mode"><span class="number" aria-hidden="true">⌂</span><span class="badge">IN PERSON · HYDERABAD</span><h3>A place to learn, together.</h3><p>Join offline abacus classes at our Vidya Nagar centre in Hyderabad. Explore hands-on learning with face-to-face guidance.</p><p>{address}</p><a class="text-link" href="abacus-classes-hyderabad.html">Explore Hyderabad classes ↗</a></article><article class="mode"><span class="number" aria-hidden="true">↗</span><span class="badge">ONLINE · FROM HOME</span><h3>Bring the classroom home.</h3><p>Choose online abacus learning when travelling to the centre does not fit your routine. Ask us about available online batches and learning materials.</p><p>A learning space, an abacus and an internet connection.</p><a class="text-link" href="online-abacus-classes.html">Explore online abacus ↗</a></article></div></section>'''

FAQ = [('Do you offer offline abacus classes in Hyderabad?','Yes. The Numbers Academy offers in-person abacus classes at 204 C Block, Vaidehi Nivas, Golden Palms, Achyuta Reddy Marg, Vidya Nagar, Hyderabad, Telangana 500044. Contact us before visiting to confirm batch availability.'),('Can my child learn abacus online?','Online abacus classes are available. Contact the academy to discuss the current batches, how lessons are conducted and the materials your child will need.'),('What will my child learn in abacus classes?','Students begin with number representation and addition and subtraction on an abacus, then progress to multi-digit calculations and mental arithmetic practice. The starting level depends on the learner’s current skills.'),('What are the fees and class timings?','Please contact the teacher for current fees, batch timings and availability. These may vary by program, level and whether you choose online or in-person learning.'),('How do I choose the right program for my child?','Share your child’s age, familiarity with arithmetic and learning goals with us. We can explain the differences between abacus, Vedic Maths and Rubik’s Cube training and discuss a suitable starting point.')]
def faq(items=FAQ):
    return '<section class="section wrap"><div class="faq"><span class="eyebrow">A LITTLE MORE CLARITY</span><h2>Good questions.<br>Simple answers.</h2>' + ''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items) + '</div></section>'

business = {'@context':'https://schema.org','@type':['LocalBusiness','EducationalOrganization'],'name':config['name'],'telephone':phone,'email':config['email'],'address':{'@type':'PostalAddress','streetAddress':config['streetAddress'],'addressLocality':'Hyderabad','addressRegion':'Telangana','postalCode':config['postalCode'],'addressCountry':'IN'},'areaServed':{'@type':'City','name':'Hyderabad'},'description':'Abacus classes in Vidya Nagar, Hyderabad and online, with Vedic Maths and Rubik’s Cube programs.'}
if domain: business.update(url=domain+'/',image=domain+'/assets/images/learning-hero.webp',logo=domain+'/assets/images/academy-logo.webp')
home = f'''<div class="wrap"><section class="hero"><div><span class="eyebrow pill">HYDERABAD &amp; ONLINE LEARNING</span><h1>Little minds.<br><em>Big possibilities.</em></h1><p>Abacus classes in Hyderabad and online that make numbers feel less daunting and more exciting. Help your child take the next step in their maths journey.</p><div class="actions"><a class="button" href="contact-page.html">Find the right class <span aria-hidden="true">↗</span></a><a class="button secondary" href="courses-page.html">Explore programs</a></div><p class="micro">Hands-on practice · Step-by-step learning · A brighter start</p></div><div class="hero-art">{image('learning-hero','Illustration of two children learning together with an abacus',1024,1024,True)}<div class="hero-tag">A little curiosity.<br>A lot of possibility.</div><div class="floating-note">Numbers become friends.<small>One bead, one idea, one step at a time.</small></div></div></section><div class="benefit-strip"><div><span aria-hidden="true">✧</span><div>Make room for curiosity<small>Explore numbers through practice</small></div></div><div><span aria-hidden="true">≋</span><div>Build a strong foundation<small>Begin with hands-on arithmetic</small></div></div><div><span aria-hidden="true">↗</span><div>Learn your way<small>In Hyderabad or from home</small></div></div></div></div><section class="section wrap"><div class="section-head"><div><span class="eyebrow">MORE THAN JUST NUMBERS</span><h2>A new favourite way to learn.</h2></div><a class="text-link" href="courses-page.html">See all programs ↗</a></div>{cards()}</section><section class="section tint"><div class="wrap split"><div>{image('practice','Hand using a soroban abacus with a pencil for arithmetic practice',1280,840,cls='learning-photo')}</div><div><span class="eyebrow">SMALL STEPS. STRONG FOUNDATIONS.</span><h2>Confidence starts<br>with “I can do this.”</h2><p>Learning is easier to enjoy when a child has a clear next step. Our programs bring together hands-on tools, guided exercises and regular practice.</p><ul class="check-list"><li>Start with concepts before moving to speed</li><li>Practise arithmetic and problem-solving skills</li><li>Move from physical beads to mental calculations</li></ul><a class="text-link" href="about-page.html">Get to know the academy ↗</a></div></div></section>{modes()}<section class="section tint"><div class="wrap"><span class="eyebrow">A SIMPLE START</span><h2>From curious to getting started.</h2><div class="grid steps"><article class="step"><h3>Say hello</h3><p>Tell us your child’s age, interests and familiarity with numbers.</p></article><article class="step"><h3>Find your fit</h3><p>Discuss programs, available batches and online or Hyderabad classes.</p></article><article class="step"><h3>Begin the journey</h3><p>Confirm the materials and next steps with the teacher, then start practising.</p></article></div></div></section>{faq()}{cta()}'''
render('index.html','Abacus Classes in Hyderabad & Online','Explore abacus classes in Vidya Nagar, Hyderabad and online at The Numbers Academy. Discover Vedic Maths and Rubik’s Cube programs. Enquire about batches.',home,business)
render('courses-page.html','Abacus, Vedic Maths & Rubik’s Cube Programs', 'Explore abacus, Vedic Maths and Rubik’s Cube programs at The Numbers Academy in Hyderabad. Ask about learning levels, online classes and batch availability.',head('Find their next “aha!” moment.','Three programs. Plenty of ways to explore. Choose a new challenge that suits your child’s interests and learning goals.','OUR PROGRAMS')+f'<section class="wrap bottom-space">{cards()}</section>'+modes()+cta())

abacus_content = head('Abacus classes for a confident start.','Learn to represent numbers, calculate with beads and build towards mental arithmetic. Join The Numbers Academy in Vidya Nagar, Hyderabad, or enquire about online abacus classes.','ABACUS · HYDERABAD & ONLINE')
abacus_content += f'<section class="wrap split bottom-space"><div><h2>From beads to mental maths.</h2><p>An abacus makes arithmetic tangible. Learners start by moving beads to represent numbers, practise addition and subtraction, and gradually learn to visualise calculations.</p><p>Regular practice gives children opportunities to work on accuracy and number familiarity. Progress depends on each learner’s starting point and practice.</p><a class="button" href="contact-page.html?course=Abacus">Ask about abacus classes ↗</a></div>{image("practice","Soroban abacus used for guided arithmetic practice",1280,840,True,"learning-photo")}</section><section class="section tint"><div class="wrap"><span class="eyebrow">ONE STEP AT A TIME</span><h2>A path from basics to bigger challenges.</h2><div class="grid"><article class="step"><span class="badge">LEVELS 1–3</span><h3>Build the basics</h3><p>Abacus introduction, number representation, single-digit addition and subtraction, and simple visualisation exercises.</p></article><article class="step"><span class="badge">LEVELS 4–6</span><h3>Grow with practice</h3><p>Multi-digit operations, calculation practice and mental maths foundations through visualisation.</p></article><article class="step"><span class="badge">LEVELS 7–10</span><h3>Take the next challenge</h3><p>More complex calculations, speed exercises and advanced mental arithmetic practice.</p></article></div></div></section>'
render('abacus-page.html','Abacus Training in Hyderabad & Online','Learn abacus arithmetic with The Numbers Academy. Explore beginner to advanced levels, offline classes in Vidya Nagar, Hyderabad and online learning.',abacus_content+modes()+faq()+cta(),{'@context':'https://schema.org','@type':'Course','name':'Abacus training','description':'Abacus training from number representation to mental arithmetic. In-person classes in Hyderabad and online learning.','provider':{'@type':'EducationalOrganization','name':config['name']}})

local = head('Abacus classes in Hyderabad.','A hands-on start to arithmetic, close to home. Learn at The Numbers Academy’s Vidya Nagar centre in Hyderabad.','OFFLINE ABACUS · VIDYA NAGAR')
local += f'''<section class="wrap split bottom-space"><div><h2>Learn with beads.<br>Practise together.</h2><p>Our offline abacus classes introduce number representation, addition and subtraction before progressing towards multi-digit and mental calculations.</p><p>Looking for abacus classes in Vidya Nagar, Hyderabad? Speak with the teacher about your child’s starting level and the current batch options.</p><div class="actions"><a class="button" href="contact-page.html?course=Abacus&amp;mode=Hyderabad">Enquire about Hyderabad classes ↗</a></div><a class="text-link" href="abacus-page.html">See the abacus curriculum</a></div><div class="info-panel"><span class="eyebrow">FIND OUR CENTRE</span><h3>The Numbers Academy</h3><address>{address}, India</address><p class="form-note">Please call before visiting to confirm availability and directions.</p><div class="actions"><a class="button secondary" href="{directions}">Get directions ↗</a><a class="button" href="tel:{phone}">Call the teacher</a></div></div></section>'''
render('abacus-classes-hyderabad.html','Offline Abacus Classes in Vidya Nagar, Hyderabad','Find offline abacus classes at The Numbers Academy in Vidya Nagar, Hyderabad 500044. Explore the curriculum and contact the teacher for fees and batch timings.',local+faq([FAQ[0],FAQ[2],FAQ[3]])+cta(),business)

online = head('Online abacus classes.<br>A world of learning, at home.','Keep curiosity growing wherever your child learns best. Ask The Numbers Academy about online abacus batches and how to get started.','ABACUS · ONLINE LEARNING')
online += f'<section class="wrap split bottom-space"><div>{image("learning-hero","Illustration of children enjoying abacus learning",1024,1024,True,"learning-photo")}</div><div><h2>A clear start for learning from home.</h2><p>Online abacus learning offers a way to explore arithmetic when travelling to the Hyderabad centre is difficult. Discuss the lesson format and available batches with the teacher before enrolling.</p><ul class="check-list"><li>A reliable internet connection and suitable device</li><li>A quiet space to follow the lesson and practise</li><li>An abacus and the learning materials advised by the teacher</li></ul><a class="button" href="contact-page.html?course=Abacus&amp;mode=Online">Ask about online batches ↗</a><p class="form-note">Confirm class timings, materials and fees with the academy.</p></div></section>'
render('online-abacus-classes.html','Online Abacus Classes for Children','Explore online abacus classes with The Numbers Academy. Learn about arithmetic practice, learning materials and how to enquire about online batch availability.',online+faq([FAQ[1],FAQ[2],FAQ[3]])+cta())

for path,title,description,img,alt,w,h,copy,topics in [
    ('vedic-math-page.html','Vedic Maths Classes in Hyderabad','Discover Vedic Maths at The Numbers Academy in Hyderabad. Explore calculation strategies for multiplication, division, squares and problem-solving.','vedic','Vedic Mathematics learning illustration',910,550,'Explore calculation patterns and methods that offer different ways to approach arithmetic. Vedic Maths practice can complement a learner’s existing knowledge of addition, subtraction, multiplication and division.',['Multiplication and division strategies','Squares and numerical patterns','Mental calculation practice','Applying methods to arithmetic problems']),
    ('rubiks-cube-page.html','Rubik’s Cube Classes in Hyderabad','Learn Rubik’s Cube solving at The Numbers Academy in Hyderabad. Explore patterns, step-by-step solving methods and guided puzzle practice.','cube','Rubik’s Cube puzzle used for solving practice',675,380,'Turn a colourful puzzle into a series of achievable steps. Learn to recognise patterns, understand cube moves and follow a solving sequence, then practise at your own pace.',['Understanding the cube and its notation','Recognising patterns and planning moves','Following a step-by-step solving method','Practising to improve fluency'])]:
    body=head(title,copy,'A NEW WAY TO THINK')+f'<section class="wrap split bottom-space"><div><h2>Make space for a new skill.</h2><ul class="check-list">'+''.join(f'<li>{topic}</li>' for topic in topics)+f'</ul><p>Contact the academy to discuss suitability, current fees and class availability.</p><a class="button" href="contact-page.html?course={quote("Vedic Maths" if img == "vedic" else "Rubik’s Cube")}">Enquire about this program ↗</a></div>{image(img,alt,w,h,True,"learning-photo")}</section>'
    render(path,title,description,body+cta())

about=head('A little curiosity can go a long way.','At The Numbers Academy, we want children to feel comfortable exploring numbers, asking questions and taking on new challenges.','ABOUT THE ACADEMY')
about+=f'<section class="section tint"><div class="wrap split"><div><h2>Learning that starts<br>with understanding.</h2><p>Our academy in Vidya Nagar, Hyderabad offers abacus training, Vedic Maths and Rubik’s Cube programs. Online abacus options help families explore learning from home.</p><p>We bring together practical tools and structured exercises, with a focus on building arithmetic foundations through practice.</p><p>Talk with the teacher about your child’s needs, the program structure and what to expect before joining.</p><a class="text-link" href="contact-page.html">Let’s talk about their next step ↗</a></div>{image("practice","Hands-on arithmetic practice with a soroban abacus",1280,840,cls="learning-photo")}</div></section>'
render('about-page.html','About Our Hyderabad Abacus Academy','Meet The Numbers Academy in Vidya Nagar, Hyderabad. Explore our approach to abacus, Vedic Maths and Rubik’s Cube learning for children.',about+modes()+cta())

contact=head('Let’s find their next step.','Tell us what you’re looking for. Speak directly with the teacher about programs, fees and batch timings.','SAY HELLO')
contact+=f'''<section class="wrap contact-grid bottom-space"><div class="form-panel"><h2>Start a conversation.</h2><p>Prepare your enquiry, then send it to the academy on WhatsApp.</p><form id="enquiry-form" data-phone="{phone.lstrip('+')}"><label for="name">Parent or guardian’s name</label><input id="name" name="name" autocomplete="name" maxlength="100" required><div class="field-row"><div><label for="course">Interested program</label><select id="course" name="course"><option>Abacus</option><option>Vedic Maths</option><option>Rubik’s Cube</option><option>Help me choose</option></select></div><div><label for="mode">Class preference</label><select id="mode" name="mode"><option>Hyderabad</option><option>Online</option><option>Help me choose</option></select></div></div><label for="message">What would you like to know? (optional)</label><textarea id="message" name="message" rows="4" maxlength="1500" placeholder="Ask about batches, fees or your child’s starting level."></textarea><button class="button" type="submit">Continue to WhatsApp ↗</button><p class="form-note">WhatsApp will open with your message ready. Review it and tap Send. This site does not store your enquiry.</p><noscript><p>JavaScript is needed to prepare your message. <a href="{whatsapp}">Contact us directly on WhatsApp</a> or call the teacher.</p></noscript></form></div><aside class="info-panel"><h3>Speak to the teacher</h3><p><a href="tel:{phone}">{phone[:3]} {phone[3:]}</a><br><a href="{whatsapp}">Open WhatsApp ↗</a></p><h3>Prefer email?</h3><a href="mailto:{email}">{email}</a><h3>Visit us in Hyderabad</h3><address>{address}, India</address><p class="form-note">Please call before visiting. Ask the teacher for current batch timings.</p><a class="button secondary" href="{directions}">Get directions ↗</a></aside></section>'''
render('contact-page.html','Contact & Enquire About Abacus Classes','Contact The Numbers Academy for abacus classes in Hyderabad or online. Call the teacher, enquire on WhatsApp or find directions to the Vidya Nagar centre.',contact,business)

reviews=head('Your experience matters.','Have you attended a class with The Numbers Academy? We would love to hear what helped and what we can improve.','FAMILY FEEDBACK')
reviews+=f'''<section class="wrap bottom-space"><div class="form-panel prose"><h2>Share feedback with the teacher.</h2><p>Send your experience directly to the academy. Public family stories will be added with permission; we do not publish sample reviews as real testimonials.</p><a class="button" href="{whatsapp}?text=Hello%20The%20Numbers%20Academy!%20I%20would%20like%20to%20share%20feedback%20about%20our%20classes.">Share feedback on WhatsApp ↗</a><p class="form-note">You can review your message before sending. Avoid sharing private details about children.</p></div></section>'''
render('comments-page.html','Share Your Learning Experience','Share feedback about The Numbers Academy’s abacus, Vedic Maths and Rubik’s Cube programs directly with the teacher.',reviews+cta())

def alias(path, target):
    canonical = f'<link rel="canonical" href="{domain}/{target}">' if domain else ''
    (ROOT / path).write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Numbers Academy</title><meta name="robots" content="noindex,follow">{canonical}<meta http-equiv="refresh" content="0;url={target}"></head><body><p>This page has moved. <a href="{target}">Continue to The Numbers Academy</a>.</p></body></html>',encoding='utf-8')
alias('educational-website.html','index.html')
alias('rubiks-cube-page (1).html','rubiks-cube-page.html')
alias('comments-app/frontend/comments-page.html','../../comments-page.html')
(ROOT / 'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /api/\n' + (f'Sitemap: {domain}/sitemap.xml\n' if domain else ''),encoding='utf-8')
if domain:
    urls = ''.join('<url><loc>'+xml_escape(domain+'/' + ('' if path=='index.html' else path))+'</loc></url>' for path in PAGES)
    (ROOT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls+'</urlset>',encoding='utf-8')
elif (ROOT / 'sitemap.xml').exists():
    (ROOT / 'sitemap.xml').unlink()
print(f'Built {len(PAGES)} pages. ' + ('Canonical URLs and sitemap configured.' if domain else 'Set the live domain in site-config.json and rebuild to enable canonical URLs and sitemap.'))
