const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const listeners = {};
const buttonListeners = {};
const attributes = {};
let open = false;
const button = {setAttribute:(key,value)=>attributes[key]=value,addEventListener:(key,fn)=>buttonListeners[key]=fn,focus:()=>{}};
const menu = {classList:{toggle:()=>open=!open,remove:()=>open=false,contains:()=>open},addEventListener:()=>{}};
const selects = {course:{options:[{value:'Abacus'}]},mode:{options:[{value:'Online'},{value:'Hyderabad'}]}};
const formListeners = {};
const form = {dataset:{phone:'919866219903'},reportValidity:()=>true,elements:{namedItem:name=>selects[name]},addEventListener:(key,fn)=>formListeners[key]=fn};
const fields = {name:'Parent & learner',course:'Abacus',mode:'Online',message:'Fees? 2 + 2 = 4 🙂'};
const window = {location:{search:'?course=Abacus&mode=Online'},matchMedia:()=>({addEventListener:()=>{}})};
const document = {querySelector:selector=>({'.menu-toggle':button,'.nav-links':menu,'#enquiry-form':form})[selector],addEventListener:(key,fn)=>listeners[key]=fn};
vm.runInNewContext(fs.readFileSync('assets/site.js','utf8'),{document,window,URLSearchParams,FormData:class{get(key){return fields[key];}},encodeURIComponent});
assert.equal(selects.mode.value,'Online');
buttonListeners.click();
assert.equal(attributes['aria-expanded'],'true');
listeners.keydown({key:'Escape'});
assert.equal(attributes['aria-expanded'],'false');
formListeners.submit({preventDefault:()=>{}});
const url = new URL(window.location.href);
assert.equal(url.hostname,'wa.me');
assert.equal(url.pathname,'/919866219903');
assert.ok(url.searchParams.get('text').includes(fields.message));
assert.ok(url.searchParams.get('text').includes(fields.name));
console.log('PASS: menu keyboard behavior, class preselection and WhatsApp destination/message encoding.');
